on:
  push:
    branches: [main]
  pull_request:

name: Test Action

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        os: [ubuntu-latest]
    name: Test the action
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: ./
        id: setup-pdm
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          allow-python-prereleases: true

      - name: Check output
        run: |
          echo ${{ steps.setup-pdm.outputs.pdm-bin }}
          echo ${{ steps.setup-pdm.outputs.pdm-version }}
          echo ${{ steps.setup-pdm.outputs.python-path }}
          echo ${{ steps.setup-pdm.outputs.python-version }}

      - name: Install dependencies
        run: pdm install -v && pdm info

      - name: Verify python version
        run: pytest
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}